version: '3'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
     - SYS_MODULE
     - mknod
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    networks:
     - cosmos

networks:
  cosmos:
    - external: true
